packages:
  - .

nodeLinker: hoisted

overrides:
  'app-builder-lib>@electron/get': 4.0.3

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  electron: true
  electron-winstaller: true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
  sharp: true
